export { createMuiRegistry, muiComponents } from './factory.js';
export type { MuiComponentName } from './factory.js';

export {
  buttonSchema,
  cardSchema,
  alertSchema,
  chipSchema,
  textFieldSchema,
  selectSchema,
  dialogSchema,
  tabsSchema,
  tableSchema,
  avatarSchema,
  accordionSchema,
  breadcrumbsSchema,
  paginationSchema,
  progressBarSchema,
  skeletonSchema,
  tooltipSchema,
  textareaSchema,
  checkboxSchema,
  radioGroupSchema,
  switchSchema,
  sliderSchema,
  formSchema,
  stepperSchema,
  statCardSchema,
  timelineSchema,
  barChartSchema,
  lineChartSchema,
  pieChartSchema,
  areaChartSchema,
  mapSchema,
} from './schemas.js';

export {
  buttonActions,
  textFieldActions,
  selectActions,
  dialogActions,
  tabsActions,
  chipActions,
  alertActions,
  accordionActions,
  paginationActions,
  textareaActions,
  checkboxActions,
  radioGroupActions,
  switchActions,
  sliderActions,
  formActions,
  stepperActions,
  mapActions,
} from './actions.js';
