export { createShadcnRegistry, shadcnComponents } from './factory.js';
export type { ShadcnComponentName } from './factory.js';

// Individual schemas for customization
export {
  buttonSchema,
  cardSchema,
  alertSchema,
  badgeSchema,
  inputSchema,
  selectSchema,
  dialogSchema,
  tabsSchema,
  tableSchema,
  avatarSchema,
  accordionSchema,
  breadcrumbsSchema,
  paginationSchema,
  progressBarSchema,
  skeletonSchema,
  tooltipSchema,
  textareaSchema,
  checkboxSchema,
  radioGroupSchema,
  switchSchema,
  sliderSchema,
  formSchema,
  stepperSchema,
  statCardSchema,
  timelineSchema,
  barChartSchema,
  lineChartSchema,
  pieChartSchema,
  areaChartSchema,
  mapSchema,
} from './schemas.js';

// Action schemas
export {
  buttonActions,
  inputActions,
  selectActions,
  dialogActions,
  tabsActions,
  accordionActions,
  paginationActions,
  textareaActions,
  checkboxActions,
  radioGroupActions,
  switchActions,
  sliderActions,
  formActions,
  stepperActions,
  mapActions,
} from './actions.js';
