name: Release

on:
  push:
    branches: [main]

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}

permissions:
  contents: write
  pull-requests: write
  id-token: write

jobs:
  release:
    name: Version & Publish
    runs-on: ubuntu-latest

    if: github.repository == 'mohammadashrafian/genuikit'

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Install pnpm
        uses: pnpm/action-setup@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 22.9.0
          cache: 'pnpm'
          registry-url: 'https://registry.npmjs.org'

      - name: Upgrade npm
        run: npm i -g npm@11.12.1

      - name: Show Node and npm versions
        run: |
          node -v
          npm -v

      - name: Install dependencies
        run: pnpm install --frozen-lockfile

      - name: Build library packages
        run: pnpm turbo build --filter='./packages/*'

      - name: Run tests
        run: pnpm turbo test --filter='./packages/*'

      - name: Create Release PR or Publish
        id: changesets
        uses: changesets/action@v1
        with:
          version: pnpm changeset version
          publish: echo "skip-changesets-publish"
          title: 'chore: version packages'
          commit: 'chore: version packages'
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Debug core package.json
        if: steps.changesets.outputs.hasChangesets == 'false'
        run: cat packages/core/package.json

      - name: Publish core only
        if: steps.changesets.outputs.hasChangesets == 'false'
        run: |
          cd packages/core
          npm publish --access public --provenance
